#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H
#include <cstdint>

#include "app/flags.h"

// This file is hand-maintained (unlike app/config.h, which is regenerated by training/generate/generate_feature_config.py).
// It holds hardware wiring and detection-behavior constants that must survive a feature-config regeneration.
// Compile-time feature flags (ENABLE_DEBUG_LOGS/ENABLE_STATUS_LED/ENABLE_LORA_COMMUNICATION) live in app/flags.h.

// --- Status LED (drivers/gpio) ---
constexpr int kStatusLedPin = 2;  // Onboard LED on most ESP32 dev boards. Update if using a dedicated external LED.

// --- Detection debounce / hysteresis (main.cpp) ---
// Raw model output must reach kDetectionEnterThreshold for kDetectionConsecutiveFrames in a row to raise an alert,
// and must drop below kDetectionExitThreshold to clear it. This avoids single-frame false positives and verdict flicker.
constexpr float kDetectionEnterThreshold = 0.65f;
constexpr float kDetectionExitThreshold = 0.35f;
constexpr int kDetectionConsecutiveFrames = 2;

// --- Watchdog (services/watchdog) ---
constexpr uint32_t kWatchdogTimeoutSeconds = 10;  // loop() must feed the watchdog more often than this or the ESP32 reboots.

// --- LoRa alert radio (services/communication, RadioLib SX127x) ---
// TODO: update these pins and the frequency to match your actual LoRa module wiring and regional regulations.
// kLoraResetPin must NOT be 14/15/32 (I2S_SCK/I2S_WS/I2S_SD in drivers/audio.h): RadioLib toggles it as a plain
// digital output during begin(), which reconfigures that pin away from its I2S peripheral function and silences the microphone.
constexpr int kLoraCsPin = 18;
constexpr int kLoraResetPin = 27;
constexpr int kLoraDio0Pin = 26;
constexpr float kLoraFrequencyMhz = 915.0f;

#endif // BOARD_CONFIG_H
