[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

# C++17
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

# board_build.partitions = huge_app.csv
build_src_filter = +<*> -<templates/>

lib_ldf_mode = chain+

lib_deps = 
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0 
    # TFLITE_ESP32 library

    jgromes/RadioLib@^7.0.0 
    # RadioLib library (for LoRa communication)

    kosme/arduinoFFT@^2.0.0 
    # arduinoFFT library (for FFT processing)