[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
# build_src_filter = +<*> -<templates/>
lib_ldf_mode = deep
lib_deps = 
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0